### ISSUE TITLE
There are still places where FileID zero is returned, which confuses linux

### ISSUE THREAD

**Issue by rminnich** [willscott/go-nfs#100]
```
[ 1811.830000] NFS: server 192.168.0.10 error: fileid changed
[ 1811.830000] fsid 0:13: expected fileid 0x0, got 0x165b98be2e784cc9
[ 1811.870000] NFS: server 192.168.0.10 error: fileid changed
[ 1811.870000] fsid 0:13: expected fileid 0x0, got 0x15e019a7babe4e62
[ 1811.900000] NFS: server 192.168.0.10 error: fileid changed
[ 1811.900000] fsid 0:13: expected fileid 0x0, got 0x8a54dff6858049b8
```
This was the result of mounting it, doing a tab complete, then an ls.

**Comment by rminnich** [comment]
Looking a bit deeper, I think every call that tryStat ought to be checked to see if the return attr needs fileid set.

**Comment by rminnich** [comment]
or, tryStat should take an [optional] handle to fill in fileid maybe.

**Comment by rminnich** [comment]
Just FYI, I'm also seeing this on OSX. 
Once I mount, the second time I ls a directory:
ls: nfs/etc: Stale NFS file handle
lrwxr-xr-x   1 root  wheel    11 Nov 18 10:13 etc

**Comment by willscott** [comment]
This may be related to a couple of the other issues that have surfaced, as we partially went from always reporting fileid 0 to sometimes reporting the underlying inode.

**Comment by willscott** [comment]
Closing this as also resulting from the issue fixed in #102

**Comment by rminnich** [comment]
oh darn. things seemed to work, but the problem is back, in spades. To recreate on osx:
osfnfs / 2049
sudo mount -t nfs -o nfsvers=3,port=2049,mountport=2049,nolock 127.0.0.1:2049 nfs
ls nfs # first time it shows the directory
ls nfs/usr
r.minnich@2840nrd-rminnic tmp % ls nfs/usr/
ls: fts_read: Stale NFS file handle

and in the osnfs window:
2023/12/20 20:44:30 [ERROR] call to 0x1006d5bb0 failed: Invalid file handle
2023/12/20 20:44:30 [ERROR] call to 0x1006d5bb0 failed: Invalid file handle
2023/12/20 20:44:30 [ERROR] call to 0x1006d5bb0 failed: Invalid file handle
2023/12/20 20:44:30 [ERROR] call to 0x1006d5bb0 failed: Invalid file handle

over and over :(

**Comment by willscott** [comment]
fileid should be getting forwarded properly through `tryStat` now.

* I wonder if this is an issue with FileID's still ,or is now an issue with handles?

**Comment by t0rr3sp3dr0** [comment]
I'm also still getting stale NFS file handles while using the latest version of the library (269dbac, at the time of writing).

```console
pedro@Pedros-MacBook-Pro Downloads % ls -@Oahl ~/Applications                                                                    
total 2924
dr-xr-xr-x@   5 root   wheel  -  160B 31 Dec  1969 .
	com.apple.FinderInfo	  32B 
drwxr-x---+ 103 pedro  staff  -  3.2K 30 Dec 21:02 ..
-rw-rw-rw-    1 root   wheel  -  1.4M 30 Dec 21:35 .VolumeIcon.icns
-rw-rw-rw-    1 root   wheel  -  406B 30 Dec 21:35 ._.

ls: /Users/pedro/Applications/IntelliJ IDEA CE.app: Stale NFS file handle
lrwxr-xr-x    1 root   wheel  -  116B 31 Dec  1969 IntelliJ IDEA CE.app

ls: /Users/pedro/Applications/Sublime Text.app: Stale NFS file handle
lrwxr-xr-x    1 root   wheel  -   91B 31 Dec  1969 Sublime Text.app

ls: /Users/pedro/Applications/Visual Studio Code.app: Stale NFS file handle
lrwxr-xr-x    1 root   wheel  -  105B 31 Dec  1969 Visual Studio Code.app
```

```console
pedro@Pedros-MacBook-Pro Downloads % ls -@Oahl ~/Applications
ls: IntelliJ IDEA CE.app: Stale NFS file handle
ls: Sublime Text.app: Stale NFS file handle
ls: Visual Studio Code.app: Stale NFS file handle
total 2921
dr-xr-xr-x@   5 root   wheel  -  160B 31 Dec  1969 .
	com.apple.FinderInfo	  32B 
drwxr-x---+ 103 pedro  staff  -  3.2K 30 Dec 21:02 ..
-rw-rw-rw-    1 root   wheel  -  1.4M 30 Dec 21:38 .VolumeIcon.icns
-rw-rw-rw-    1 root   wheel  -  406B 30 Dec 21:38 ._.
ls: fts_read: Stale NFS file handle
```

The problem seems related to symbolic links. Above, all `*.app` are symbolic links to directories using their absolute paths. I'm also getting this error message on the client: `nfs loadattrcache vnode changed type, was 5 now 2`. Meaning that the vnode type was `VLNK` and now is `VDIR`.

I've added some logging, and my FS implementation is indeed returning different vnode types for those files. But that's because the NFS library is calling `billy.Filesystem#ReadDir`, that _"If the entry denotes a symbolic link, Info reports the information about the link itself, not the link's target."_, and then it calls `billy.Filesystem#Stat` instead of `billy.Filesystem#Lstat`. So the vnode type will always change.

**Comment by t0rr3sp3dr0** [comment]
This patch addressed my problem: https://github.com/t0rr3sp3dr0/go-nfs/commit/ab062303c33b645dc9c571f63b0f9bbfdb26a883

But I'm not sure if changing the implementation of `tryStat` to always use `billy.Filesystem#Lstat` is something we can do. I think we need a `tryLstat` and move to this new function on a case-by-case basis.
